# Linear Algebra in Python

Developed for [Applied Mathematics 584, Autumn Quarter 2016](http://faculty.washington.edu/rjl/classes/am584a2016/) at the University of Washington.

This notebook gives a brief introduction to doing linear algebra in Python using the [NumPy](http://www.numpy.org/) module. See also [NumPy Basics](http://docs.scipy.org/doc/numpy-dev/user/basics.html)

The first cell contains a Jupyter "magic" command that loads Numpy and also [Matplotlib](http://matplotlib.org/) which contains plotting commands similar to Matlab's.  The `inline` option makes plots appear in the notebook.


In [4]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Take a look at [Numpy for Matlab Users](http://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html) for a list of linear algebra commands in Python and how they relate to Matlab.

Note that there is a `matrix` class in Python that gives operations more the flavor of Matlab, but in the notebooks for this class I will only use the standard Numpy `ndarray` class for reasons described in [Numpy for Matlab Users](http://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html).  This is a general class for n-dimensional arrays, not just matrices.   

Here are some examples and additional hints.

## Lists

A Python list can contain objects of many different types, for example the list below contains three objects: a real number, an integer, and a string.  Note that Python indexing starts at 0, unlike Matlab.  Note also that `len(L)` returns the length of `L` and `range(n)` is the list $[0,1,\ldots,n-1]$, i.e. the set of indices of `L`.

In [17]:
L = [1.32, 5, 'seven']
for i in range(len(L)):
    print "item %s of L is %s of type %s"  % (i, L[i], type(L[i]))

item 0 of L is 1.32 of type <type 'float'>
item 1 of L is 5 of type <type 'int'>
item 2 of L is seven of type <type 'str'>


## NumPy 1-dimensional array

For vectors of numbers that all have the same type, it is much better to use a NumPy array -- both more efficient for large arrays and also many numerical functions we need are implemented for arrays.

Note in this example that 5 and 7 are stored as floats since 1.32 is a float and so all elements are converted to floats.

In [18]:
x = array([1.32, 5, 7])
for i in range(len(x)):
    print "item %s of x is %s of type %s"  % (i, x[i], type(x[i]))

item 0 of x is 1.32 of type <type 'numpy.float64'>
item 1 of x is 5.0 of type <type 'numpy.float64'>
item 2 of x is 7.0 of type <type 'numpy.float64'>


Note that in Matlab, which was designed specifically for linear algebra, the basic data structure is a matrix.  A 1-dimensional vector is stored as a matrix with one column (or one row) and there is a distinction between a column vector and a row vector.  You can transpose one to get the other.

In NumPy, a 1-dimensional array is really a 1-dimensional array, not a row or column vector, so transposing has no effect:

In [9]:
x = array([1., 2, 3])
print 'x = ',x
print 'x has shape', x.shape

y = x.T  # transpose
print 'y = ',y
print 'y has shape', y.shape

x =  [ 1.  2.  3.]
x has shape (3,)
y =  [ 1.  2.  3.]
y has shape (3,)


You can define a 1D array as above by applying the NumPy `array` function to a list of numbers.  Or there are other NumPy functions that return a 1D array, such as the `linspace` function that works as in Matlab:

In [20]:
z = linspace(0,2,5)
z

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

## Two-dimensional arrays

A 2D array can be defined by applying the NumPy `array` function to a list of lists:

In [53]:
A = array([[1., 2, 3], [4,5,6]])
print 'A = \n', A  # \n means new line

A = 
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


You can define row vectors and column vectors like Matlab does, e.g.:

In [55]:
u = array([[1., 2, 3]])
print 'u = ', u

v = u.T  
print '\nv = \n', v

u =  [[ 1.  2.  3.]]

v = 
[[ 1.]
 [ 2.]
 [ 3.]]


## Matrix-vector multiplication

NumPy arrays are a general data structure that can be use for storing many things, with as many dimensions as you want.  So there is no assumption that 2D arrays are matrices or that you are doing linear algebra.  So if you want to multiply `A` and `v` for example, with `v` as defined above, you cannot do this as `A*v` as in matlab.  Instead use the `dot` function:

In [14]:
print dot(A, v)

[[ 14.]
 [ 32.]]


## Matrix-matrix multiplication

The `dot` function can also be used for matrix-matrix multiplication.  For example, with $A$ defined as above (a $2\times 3$ matrix), we can compute $A^TA$ via:

In [21]:
print dot(A.T, A)

[[ 17.  22.  27.]
 [ 22.  29.  36.]
 [ 27.  36.  45.]]


## Slicing an array

You can extract a set of columns of `A`, for example, by using the `:` notation similar to Matlab.  But note that `i:j` refers to columns `i, i+1, ..., j-1` (it does not include column `j`).  Also remember that the first column has index `0` in Python.  You can also use `-1` to refer to the last column, `-2` to the next-to-last, etc.

Here are some examples:

In [37]:
print "A =\n", A  # \n means new line
print "\nA[:, 0:2] =\n", A[:,0:2]
print "\nA[:, 1:] =\n", A[:,1:]
print "\nA[:, :-1] =\n", A[:,:-1]
print "\nA[:, 2] =\n", A[:,2]
print "\nA[:, 2:3] =\n", A[:,2:3]

A =
[[ 1.  2.  3.]
 [ 4.  5.  6.]]

A[:, 0:2] =
[[ 1.  2.]
 [ 4.  5.]]

A[:, 1:] =
[[ 2.  3.]
 [ 5.  6.]]

A[:, :-1] =
[[ 1.  2.]
 [ 4.  5.]]

A[:, 2] =
[ 3.  6.]

A[:, 2:3] =
[[ 3.]
 [ 6.]]


Note from the last two examples that `A[:,2]` and `A[:,2:3]` both return only the last column (index 2) but the first one returns it as a 1D array and the second as a 2D array!  In many applications extracting a single row or column of a 2D array should return a 1D array, but for linear algebra we might prefer the latter since a single column of a matrix should be a column vector.  The latter form is used in the next example.

## Matrix-vector multiplication as a linear combination of column vectors

Lecture 1 of Trefethen and Bau stresses that matrix-vector multiplication can be viewed as computing a linear combination of column vectors. Here's how we might compute $y = Av$ that we found above via `dot(A, V)` by instead writing a loop to accumulate this linear combination:

In [56]:
m,n = shape(A)  # number of rows and columns of A
print "Each column of A has %s elements, so product y=Av will too"  % m

y = zeros((m,1))  # initialize to zero-vector of correct shape (2D array with shape m by 1)
for j in range(n):
    # loop over columns and add in v[j] times j'th column of A:
    y += A[:,j:j+1]*v[j]   # use j:j+1 to select only j'th column as vector

print "\ny =\n", y

Each column of A has 2 elements, so product y=Av will too

y =
[[ 14.]
 [ 32.]]


## Rank of a matrix

To compute the rank of a matrix and other linear algebra quantities, we first import the `numpy.linalg` package.  See  [Numpy for Matlab Users](http://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html) and other NumPy references for more functions.

In [43]:
from numpy import linalg

In [44]:
print "The rank of A is ", linalg.matrix_rank(A)

The rank of A is  2


This should not be surprising: since the matrix has only 2 rows the rank cannot be larger than 2, and the rows are linearly independent so it has rank 2.

## Matrix inverse

For a square nonsingular matrix, we can compute the inverse using `linalg.inv`.  We illustrate with the matrix $B = AA^T$ which is a full rank $2\times 2$ matrix:

In [47]:
B = dot(A, A.T)
print "B =\n", B

Binv = linalg.inv(B)
print "\nThe inverse of B is \n", Binv

print "\nThe product of the two is\n", dot(Binv, B)

B =
[[ 14.  32.]
 [ 32.  77.]]

The inverse of B is 
[[ 1.42592593 -0.59259259]
 [-0.59259259  0.25925926]]

The product of the two is
[[ 1.  0.]
 [ 0.  1.]]


## Solving a linear system

If you want to solve a linear system, say $Bx = y$ with the matrix above, you could multiply by the inverse but as you probably know, in general it is better to just solve the linear system.  In Matlab this can be done using the backslash operator.  In NumPy we use `linalg.solve`:

In [57]:
xtrue = array([[3.], [-2.]])
print "For comparison, the true solution will be xtrue =\n", xtrue

# compute right hand side:
y = dot(B, xtrue)
print "\nFrom this we generate the right hand side y = B*xtrue = \n", y
print "\nMultiplying Binv * y gives\n", dot(Binv,y)

# Solve system:
x = linalg.solve(B, y)
print "\nSolving system directly gives\n", x

For comparison, the true solution will be xtrue =
[[ 3.]
 [-2.]]

From this we generate the right hand side y = B*xtrue = 
[[-22.]
 [-58.]]

Multiplying Binv * y gives
[[ 3.]
 [-2.]]

Solving system directly gives
[[ 3.]
 [-2.]]
